### ISSUE TITLE
Feature Request: More Examples

### ISSUE THREAD

**Issue by Saijin-Naib** [cbrgm/mastodon-github-action#2]
I'm interested in using this script, but I don't know how to interact with non-static elements, as the examples show only static text toots.

For instance, how does one toot a tagged build? A release? A new issue? Opened PR? Merged PR?

These are the things I think would be really powerful to use with this action, but I do not know where to begin.

**Comment by cbrgm** [comment]
Hey, 

feel free to contribute some examples. [Here](https://github.com/phpstan/phpstan-webmozart-assert/blob/1.2.x/.github/workflows/release-toot.yml) for for example a workflow which publishes a toot on new release tags. You can find a couple of other examples looking through repositories and workflows using this action (see [dependabots](https://github.com/cbrgm/mastodon-github-action/network/dependents))

Cheers!
