### ISSUE TITLE
FetchError with reason: socket hang up

### ISSUE THREAD

**Issue by boozook** [cbrgm/mastodon-github-action#31]
```
FetchError: request to ***/api/v1/instance failed, reason: socket hang up
```

[Example](https://github.com/boozook/playdate/actions/runs/6668240572/job/18123495984#step:3:16)

**Comment by cbrgm** [comment]
Hey probably it's way to late for my response. I'm about to release `v2` of this acton probably today which will probably resolve this issue.

**Comment by cbrgm** [comment]
@boozook ah, and sorry for the short answer here. Thanks for reporting this issue! 😄

**Comment by boozook** [comment]
Thank you so much! I updated.
