### ISSUE TITLE
API call error: unsupported protocol scheme

### ISSUE THREAD

**Issue by boozook** [cbrgm/mastodon-github-action#48]
Action version: 2.0.1
Token: write:favourites write:media write:statuses crypto

Action is [here](https://github.com/boozook/playdate/blob/main/.github/workflows/post.yml#L28-L47).
[Error](https://github.com/boozook/playdate/actions/runs/7861182552/job/21449277591#step:4:25):
```text
Error posting status: API call error: Post "/api/v1/statuses": unsupported protocol scheme ""
```

Please, could you explain what that means and how to fix it? 🙄

**Comment by cbrgm** [comment]
Can you double-check your `MASTODON_URL` secret? I suppose it's missing the `https://` or `http://` prefix. You have to provide the full url including the scheme.

**Comment by boozook** [comment]
Seems to you're right, thanks!
